<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="SPA-Web-Form.aspx.cs" Inherits="SoftwareProcessAid.SPA_Web_Form"%>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>Formal Sciences</title>
    <style> 
            body {
                background-color: rgb(0,0,64);
            }
    </style>
</head>
<body>
    <h1>Process Project Product</h1>
    <form id="form1" runat="server">
        <div>
            <p>"Use a SDLC (Waterfall/Agile/etc.) as a process for projects for products, & project size (small/medium/large) for timespan."</p>
            <p>"With regards to process elements, six analysis/design layers are architectural (where), data/class (what), interface (how), procedural (when), component (why), and deployment (who)."</p>
            <p>"Diagrams by modeling spaces may be recommended: problem (use case & activity) during planning, solution (class & sequence) during analysis & design, and architectural (component & deployment) during implementation/etc."</p>
            <p>Choose from the following topics: formal, natural, social, other.</p>
        </div>
    </form>
    <h1>Combinatorics</h1>
    <p>
        Categories may comprise of sets/groups/topologies/etc.
        How many boxes?
        read boxes
        How many balls?
        read balls
        possibilities = balls^boxes
        if both are distinct, then there are possibilities.
    </p>
    <h1>OOP</h1>
    <p>
        Name, attributes, methods: make up a class (diagram).
    </p>
    <h1>Password Passphrase<h1>
    <p>
        Use a password; a passphrase may be used also for 2FA
    <p>
    <h1>Complex Systems Theory<h1>
    <p>
        Complexity theories can be educationally very useful.
    <p>
    <h1>Security Controls<h1>
    <p>
      Rate the effectiveness of each security control type:
      Access Control = "ACCESS CONTROL POLICY AND PROCEDURES", "ACCOUNT MANAGEMENT", "ACCESS ENFORCEMENT", "INFORMATION FLOW ENFORCEMENT", "SEPARATION OF DUTIES", "LEAST PRIVILEGE", "UNSUCCESSFUL LOGON ATTEMPTS", "SYSTEM USE NOTIFICATION", "PREVIOUS LOGON (ACCESS) NOTIFICATION", "CONCURRENT SESSION CONTROL", "SESSION LOCK", "SESSION TERMINATION", "SUPERVISION AND REVIEW ACCESS CONTROL", "PERMITTED ACTIONS WITHOUT IDENTIFICATION OR AUTHENTICATION", "AUTOMATED MARKING", "SECURITY ATTRIBUTES", "REMOTE ACCESS", "WIRELESS ACCESS", "ACCESS CONTROL FOR MOBILE DEVICES", "USE OF EXTERNAL INFORMATION SYSTEMS", "INFORMATION SHARING", "PUBLICLY ACCESSIBLE CONTENT", "DATA MINING PROTECTION", "ACCESS CONTROL DECISIONS", "REFERENCE MONITOR."
      Awareness and Training = "SECURITY AWARENESS AND TRAINING POLICY AND PROCEDURES", "SECURITY AWARENESS TRAINING", "ROLE-BASED SECURITY TRAINING", "SECURITY TRAINING RECORDS", "CONTACTS WITH SECURITY GROUPS AND ASSOCIATIONS."
      Audit and Accountability = "AUDIT AND ACCOUNTABILITY POLICY AND PROCEDURES", "AUDIT EVENTS", "CONTENT OF AUDIT RECORDS", "AUDIT STORAGE CAPACITY", "RESPONSE TO AUDIT PROCESSING FAILURES", "AUDIT REVIEW, ANALYSIS, AND REPORTING", "AUDIT REDUCTION AND REPORT GENERATION", "TIME STAMPS", "PROTECTION OF AUDIT INFORMATION", "NON-REPUDIATION", "AUDIT RECORD RETENTION", "AUDIT GENERATION", "MONITORING FOR INFORMATION DISCLOSURE", "SESSION AUDIT", "ALTERNATE AUDIT CAPABILITY", "CROSS-ORGANIZATIONAL AUDITING."
      Security Assessment And Authorization = "SECURITY ASSESSMENT AND AUTHORIZATION POLICY AND PROCEDURES", "SECURITY ASSESSMENTS", "SYSTEM INTERCONNECTIONS", "SECURITY CERTIFICATION", "PLAN OF ACTION AND MILESTONES", "SECURITY AUTHORIZATION", "CONTINUOUS MONITORING", "PENETRATION TESTING", "INTERNAL SYSTEM CONNECTIONS."
      Configuration Management = "CONFIGURATION MANAGEMENT POLICY AND PROCEDURES", "BASELINE CONFIGURATION", "CONFIGURATION CHANGE CONTROL", "SECURITY IMPACT ANALYSIS", "ACCESS RESTRICTIONS FOR CHANGE", "CONFIGURATION SETTINGS", "LEAST FUNCTIONALITY", "INFORMATION SYSTEM COMPONENT INVENTORY", "CONFIGURATION MANAGEMENT PLAN", "SOFTWARE USAGE RESTRICTIONS", "USER-INSTALLED SOFTWARE."
      Contingency Planning = "CONTINGENCY PLANNING POLICY AND PROCEDURES", "CONTINGENCY PLAN", "CONTINGENCY TRAINING", "CONTINGENCY PLAN TESTING", "CONTINGENCY PLAN UPDATE", "ALTERNATE STORAGE SITE", "ALTERNATE PROCESSING SITE", "TELECOMMUNICATIONS SERVICES", "INFORMATION SYSTEM BACKUP", "INFORMATION SYSTEM RECOVERY AND RECONSTITUTION", "ALTERNATE COMMUNICATIONS PROTOCOLS", "SAFE MODE", "ALTERNATIVE SECURITY MECHANISMS."
      Identification and Authentication = "IDENTIFICATION AND AUTHENTICATION POLICY AND PROCEDURES", "IDENTIFICATION AND AUTHENTICATION (ORGANIZATIONAL USERS)", "DEVICE IDENTIFICATION AND AUTHENTICATION", "IDENTIFIER MANAGEMENT", "AUTHENTICATOR MANAGEMENT", "AUTHENTICATOR FEEDBACK", "CRYPTOGRAPHIC MODULE AUTHENTICATION", "IDENTIFICATION AND AUTHENTICATION (NON-ORGANIZATIONAL USERS)", "SERVICE IDENTIFICATION AND AUTHENTICATION", "ADAPTIVE IDENTIFICATION AND AUTHENTICATION", "RE-AUTHENTICATION."
      Incident Response = "INCIDENT RESPONSE POLICY AND PROCEDURES", "INCIDENT RESPONSE TRAINING", "INCIDENT RESPONSE TESTING", "INCIDENT HANDLING", "INCIDENT MONITORING", "INCIDENT REPORTING", "INCIDENT RESPONSE ASSISTANCE", "INCIDENT RESPONSE PLAN", "INFORMATION SPILLAGE RESPONSE", "INTEGRATED INFORMATION SECURITY ANALYSIS TEAM."
      Maintenance = "SYSTEM MAINTENANCE POLICY AND PROCEDURES", "CONTROLLED MAINTENANCE", "MAINTENANCE TOOLS", "NONLOCAL MAINTENANCE", "MAINTENANCE PERSONNEL", "TIMELY MAINTENANCE."
      Media Protection = "MEDIA PROTECTION POLICY AND PROCEDURES", "MEDIA ACCESS", "MEDIA MARKING", "MEDIA STORAGE", "MEDIA TRANSPORT", "MEDIA SANITIZATION", "MEDIA USE", "MEDIA DOWNGRADING."
      Physical and Environmental Protection = "PHYSICAL AND ENVIRONMENTAL PROTECTION POLICY AND PROCEDURES", "PHYSICAL ACCESS AUTHORIZATIONS", "PHYSICAL ACCESS CONTROL", "ACCESS CONTROL FOR TRANSMISSION MEDIUM", "ACCESS CONTROL FOR OUTPUT DEVICES", "MONITORING PHYSICAL ACCESS", "VISITOR CONTROL", "VISITOR ACCESS RECORDS", "POWER EQUIPMENT AND CABLING", "EMERGENCY SHUTOFF", "EMERGENCY POWER", "EMERGENCY LIGHTING", "FIRE PROTECTION", "TEMPERATURE AND HUMIDITY CONTROLS", "WATER DAMAGE PROTECTION", "DELIVERY AND REMOVAL", "ALTERNATE WORK SITE", "LOCATION OF INFORMATION SYSTEM COMPONENTS", "INFORMATION LEAKAGE", "ASSET MONITORING AND TRACKING."
      Planning = "SECURITY PLANNING POLICY AND PROCEDURES", "SYSTEM SECURITY PLAN", "SYSTEM SECURITY PLAN UPDATE", "RULES OF BEHAVIOR", "PRIVACY IMPACT ASSESSMENT", "SECURITY-RELATED ACTIVITY PLANNING", "SECURITY CONCEPT OF OPERATIONS", "INFORMATION SECURITY ARCHITECTURE", "CENTRAL MANAGEMENT."
      Personnel Security = "PERSONNEL SECURITY POLICY AND PROCEDURES", "POSITION RISK DESIGNATION", "PERSONNEL SCREENING", "PERSONNEL TERMINATION", "PERSONNEL TRANSFER", "ACCESS AGREEMENTS", "THIRD-PARTY PERSONNEL SECURITY", "PERSONNEL SANCTIONS."
      Risk Assessment = "RISK ASSESSMENT POLICY AND PROCEDURES", "SECURITY CATEGORIZATION", "RISK ASSESSMENT", "RISK ASSESSMENT UPDATE", "VULNERABILITY SCANNING", "TECHNICAL SURVEILLANCE COUNTERMEASURES SURVEY."
      System and Services Acquisition = "SYSTEM AND SERVICES ACQUISITION POLICY AND PROCEDURES", "ALLOCATION OF RESOURCES", "SYSTEM DEVELOPMENT LIFE CYCLE", "ACQUISITION PROCESS", "INFORMATION SYSTEM DOCUMENTATION", "SOFTWARE USAGE RESTRICTIONS", "USER-INSTALLED SOFTWARE", "SECURITY ENGINEERING PRINCIPLES", "EXTERNAL INFORMATION SYSTEM SERVICES", "DEVELOPER CONFIGURATION MANAGEMENT", "DEVELOPER SECURITY TESTING AND EVALUATION", "SUPPLY CHAIN PROTECTION", "TRUSTWORTHINESS", "CRITICALITY ANALYSIS", "DEVELOPMENT PROCESS, STANDARDS, AND TOOLS", "DEVELOPER-PROVIDED TRAINING", "DEVELOPER SECURITY ARCHITECTURE AND DESIGN", "TAMPER RESISTANCE AND DETECTION", "COMPONENT AUTHENTICITY", "CUSTOMIZED DEVELOPMENT OF CRITICAL COMPONENTS", "DEVELOPER SCREENING", "UNSUPPORTED SYSTEM COMPONENTS."
      System and Communications Protection = "SYSTEM AND COMMUNICATIONS PROTECTION POLICY AND PROCEDURES", "APPLICATION PARTITIONING", "SECURITY FUNCTION ISOLATION", "INFORMATION IN SHARED RESOURCES", "DENIAL OF SERVICE PROTECTION", "RESOURCE AVAILABILITY", "BOUNDARY PROTECTION", "TRANSMISSION CONFIDENTIALITY AND INTEGRITY", "TRANSMISSION CONFIDENTIALITY", "NETWORK DISCONNECT", "TRUSTED PATH", "CRYPTOGRAPHIC KEY ESTABLISHMENT AND MANAGEMENT", "CRYPTOGRAPHIC PROTECTION", "PUBLIC ACCESS PROTECTIONS", "COLLABORATIVE COMPUTING DEVICES", "TRANSMISSION OF SECURITY ATTRIBUTES", "PUBLIC KEY INFRASTRUCTURE CERTIFICATES", "MOBILE CODE", "VOICE OVER INTERNET PROTOCOL", "SECURE NAME / ADDRESS RESOLUTION SERVICE (AUTHORITATIVE SOURCE)", "SECURE NAME / ADDRESS RESOLUTION SERVICE (RECURSIVE OR CACHING RESOLVER)", "ARCHITECTURE AND PROVISIONING FOR NAME / ADDRESS RESOLUTION SERVICE", "SESSION AUTHENTICITY", "FAIL IN KNOWN STATE", "THIN NODES", "HONEYPOTS", "PLATFORM-INDEPENDENT APPLICATIONS", "PROTECTION OF INFORMATION AT REST", "HETEROGENEITY", "CONCEALMENT AND MISDIRECTION", "COVERT CHANNEL ANALYSIS", "INFORMATION SYSTEM PARTITIONING", "TRANSMISSION PREPARATION INTEGRITY", "NON-MODIFIABLE EXECUTABLE PROGRAMS", "HONEYCLIENTS", "DISTRIBUTED PROCESSING AND STORAGE", "OUT-OF-BAND CHANNELS", "OPERATIONS SECURITY", "PROCESS ISOLATION", "WIRELESS LINK PROTECTION", "PORT AND I/O DEVICE ACCESS", "SENSOR CAPABILITY AND DATA", "USAGE RESTRICTIONS", "DETONATION CHAMBERS."
      System and Information Integrity = "SYSTEM AND INFORMATION INTEGRITY POLICY AND PROCEDURES", "FLAW REMEDIATION", "MALICIOUS CODE PROTECTION", "INFORMATION SYSTEM MONITORING", "SECURITY ALERTS, ADVISORIES, AND DIRECTIVES", "SECURITY FUNCTION VERIFICATION", "SOFTWARE, FIRMWARE, AND INFORMATION INTEGRITY", "SPAM PROTECTION", "INFORMATION INPUT RESTRICTIONS", "INFORMATION INPUT VALIDATION", "ERROR HANDLING", "INFORMATION HANDLING AND RETENTION", "PREDICTABLE FAILURE PREVENTION", "NON-PERSISTENCE", "INFORMATION OUTPUT FILTERING", "MEMORY PROTECTION", "FAIL-SAFE PROCEDURES."
      Program Management = "INFORMATION SECURITY PROGRAM PLAN", "SENIOR INFORMATION SECURITY OFFICER", "INFORMATION SECURITY RESOURCES", "PLAN OF ACTION AND MILESTONES PROCESS", "INFORMATION SYSTEM INVENTORY", "INFORMATION SECURITY MEASURES OF PERFORMANCE", "ENTERPRISE ARCHITECTURE", "CRITICAL INFRASTRUCTURE PLAN", "RISK MANAGEMENT STRATEGY", "SECURITY AUTHORIZATION PROCESS", "MISSION/BUSINESS PROCESS DEFINITION", "INSIDER THREAT PROGRAM", "INFORMATION SECURITY WORKFORCE", "TESTING, TRAINING, AND MONITORING", "CONTACTS WITH SECURITY GROUPS AND ASSOCIATIONS."
      
      Rate the value of each asset category:
      data
      network infrastructure
      applications
      devices (like computers and mobile phones)
      user accounts
      intellectual property
      system configurations
    <p>
    <h1>3D Geometric Numbers<h1>
    <p>
        These are useful geometric numbers: Tetrahedral, Square Pyramidal, Triangular Bipyramid, Triangular Prism, Octahedral, Cubic; 1, 4, 5, 6, 8, 10, 12, 14, 20, 27, 30, 34, 35, 42, 54, 55, 56, 64
    <p>
</body>
</html>
